export const taxIdTypes = [
  {
    type: "ae_trn",
    code: "AE TRN",
    name: "United Arab Emirates",
    emoji: "🇦🇪",
    placeholder: "123456789012345",
  },
  {
    type: "au_abn",
    code: "AU ABN",
    name: "Australia",
    emoji: "🇦🇺",
    placeholder: "123456789012",
  },
  {
    type: "au_arn",
    code: "AU ARN",
    name: "Australia",
    emoji: "🇦🇺",
    placeholder: "123456789012",
  },
  {
    type: "bg_uic",
    code: "BG UIC",
    name: "Bulgaria",
    emoji: "🇧🇬",
    placeholder: "BG123456789",
  },
  {
    type: "br_cnpj",
    code: "BR CNPJ",
    name: "Brazil",
    emoji: "🇧🇷",
    placeholder: "12.345.678/0001-23",
  },
  {
    type: "br_cpf",
    code: "BR CPF",
    name: "Brazil",
    emoji: "🇧🇷",
    placeholder: "123.456.789-01",
  },
  {
    type: "ca_bn",
    code: "CA BN",
    name: "Canada",
    emoji: "🇨🇦",
    placeholder: "123456789",
  },
  {
    type: "ca_gst_hst",
    code: "CA GST/HST",
    name: "Canada",
    emoji: "🇨🇦",
    placeholder: "123456789",
  },
  {
    type: "ca_pst_bc",
    code: "CA PST-BC",
    name: "Canada",
    emoji: "🇨🇦",
    placeholder: "123456789",
  },
  {
    type: "ca_pst_mb",
    code: "CA PST-MB",
    name: "Canada",
    emoji: "🇨🇦",
    placeholder: "123456789",
  },
  {
    type: "ca_pst_sk",
    code: "CA PST-SK",
    name: "Canada",
    emoji: "🇨🇦",
    placeholder: "123456789",
  },
  {
    type: "ca_qst",
    code: "CA QST",
    name: "Canada",
    emoji: "🇨🇦",
    placeholder: "123456789",
  },
  {
    type: "ch_vat",
    code: "CH VAT",
    name: "Switzerland",
    emoji: "🇨🇭",
    placeholder: "CHE-123.456.789 MWST",
  },
  {
    type: "cl_tin",
    code: "CL TIN",
    name: "Chile",
    emoji: "🇨🇱",
    placeholder: "12345678-9",
  },
  {
    type: "eg_tin",
    code: "EG TIN",
    name: "Egypt",
    emoji: "🇪🇬",
    placeholder: "123456789012",
  },
  {
    type: "es_cif",
    code: "ES CIF",
    name: "Spain",
    emoji: "🇪🇸",
    placeholder: "A12345678",
  },
  {
    type: "eu_oss_vat",
    code: "EU OSS VAT",
    name: "European Union",
    emoji: "🇪🇺",
    placeholder: "XX123456789",
  },
  {
    type: "eu_vat",
    code: "AT VAT",
    name: "Austria",
    emoji: "🇦🇹",
    placeholder: "ATU12345678",
  },
  {
    type: "eu_vat",
    code: "DE VAT",
    name: "Germany",
    emoji: "🇩🇪",
    placeholder: "DE123456789",
  },
  {
    type: "eu_vat",
    code: "BE VAT",
    name: "Belgium",
    emoji: "🇧🇪",
    placeholder: "BE0123456789",
  },
  {
    type: "eu_vat",
    code: "BG VAT",
    name: "Bulgaria",
    emoji: "🇧🇬",
    placeholder: "BG123456789",
  },
  {
    type: "eu_vat",
    code: "CY VAT",
    name: "Cyprus",
    emoji: "🇨🇾",
    placeholder: "CY12345678L",
  },
  {
    type: "eu_vat",
    code: "DK VAT",
    name: "Denmark",
    emoji: "🇩🇰",
    placeholder: "DK12345678",
  },
  {
    type: "eu_vat",
    code: "EE VAT",
    name: "Estonia",
    emoji: "🇪🇪",
    placeholder: "EE123456789",
  },
  {
    type: "eu_vat",
    code: "GR VAT",
    name: "Greece",
    emoji: "🇬🇷",
    placeholder: "EL123456789",
  },
  {
    type: "eu_vat",
    code: "ES VAT",
    name: "Spain",
    emoji: "🇪🇸",
    placeholder: "ESX12345678",
  },
  {
    type: "eu_vat",
    code: "FI VAT",
    name: "Finland",
    emoji: "🇫🇮",
    placeholder: "FI12345678",
  },
  {
    type: "eu_vat",
    code: "FR VAT",
    name: "France",
    emoji: "🇫🇷",
    placeholder: "FRXX123456789",
  },
  {
    type: "eu_vat",
    code: "HR VAT",
    name: "Croatia",
    emoji: "🇭🇷",
    placeholder: "HR12345678901",
  },
  {
    type: "eu_vat",
    code: "IE VAT",
    name: "Ireland",
    emoji: "🇮🇪",
    placeholder: "IE1X12345X",
  },
  {
    type: "eu_vat",
    code: "IT VAT",
    name: "Italy",
    emoji: "🇮🇹",
    placeholder: "IT12345678901",
  },
  {
    type: "eu_vat",
    code: "LT VAT",
    name: "Lithuania",
    emoji: "🇱🇹",
    placeholder: "LT123456789",
  },
  {
    type: "eu_vat",
    code: "LU VAT",
    name: "Luxembourg",
    emoji: "🇱🇺",
    placeholder: "LU12345678",
  },
  {
    type: "eu_vat",
    code: "LV VAT",
    name: "Latvia",
    emoji: "🇱🇻",
    placeholder: "LV12345678901",
  },
  {
    type: "eu_vat",
    code: "MT VAT",
    name: "Malta",
    emoji: "🇲🇹",
    placeholder: "MT12345678",
  },
  {
    type: "eu_vat",
    code: "NL VAT",
    name: "Netherlands",
    emoji: "🇳🇱",
    placeholder: "NL123456789B01",
  },
  {
    type: "eu_vat",
    code: "PL VAT",
    name: "Poland",
    emoji: "🇵🇱",
    placeholder: "PL1234567890",
  },
  {
    type: "eu_vat",
    code: "PT VAT",
    name: "Portugal",
    emoji: "🇵🇹",
    placeholder: "PT123456789",
  },
  {
    type: "eu_vat",
    code: "RO VAT",
    name: "Romania",
    emoji: "🇷🇴",
    placeholder: "RO1234567891",
  },
  {
    type: "eu_vat",
    code: "SE VAT",
    name: "Sweden",
    emoji: "🇸🇪",
    placeholder: "SE123456789101",
  },
  {
    type: "eu_vat",
    code: "SI VAT",
    name: "Slovenia",
    emoji: "🇸🇮",
    placeholder: "SI12345678",
  },
  {
    type: "eu_vat",
    code: "SK VAT",
    name: "Slovakia",
    emoji: "🇸🇰",
    placeholder: "SK1234567890",
  },
  {
    type: "eu_vat",
    code: "XI VAT",
    name: "Northern Ireland",
    emoji: "🇮🇪",
    placeholder: "XI123456789",
  },
  {
    type: "eu_vat",
    code: "GE VAT",
    name: "Georgia",
    emoji: "🇬🇪",
    placeholder: "GE123456789",
  },
  {
    type: "eu_vat",
    code: "CZ VAT",
    name: "Czech Republic",
    emoji: "🇨🇿",
    placeholder: "CZ12345678",
  },
  {
    type: "gb_vat",
    code: "GB VAT",
    name: "United Kingdom",
    emoji: "🇬🇧",
    placeholder: "GB123456789",
  },
  {
    type: "ge_vat",
    code: "GE VAT",
    name: "Georgia",
    emoji: "🇬🇪",
    placeholder: "GE123456789",
  },
  {
    type: "hk_br",
    code: "HK BR",
    name: "Hong Kong",
    emoji: "🇭🇰",
    placeholder: "12345678",
  },
  {
    type: "hu_tin",
    code: "HU TIN",
    name: "Hungary",
    emoji: "🇭🇺",
    placeholder: "13804079-2-13",
  },
  {
    type: "hu_vat",
    code: "HU VAT",
    name: "Hungary",
    emoji: "🇭🇺",
    placeholder: "HU12345678",
  },
  {
    type: "id_npwp",
    code: "ID NPWP",
    name: "Indonesia",
    emoji: "🇮🇩",
    placeholder: "123.456.7-8910.000",
  },
  {
    type: "il_vat",
    code: "IL VAT",
    name: "Israel",
    emoji: "🇮🇱",
    placeholder: "123456789",
  },
  {
    type: "in_gst",
    code: "IN GST",
    name: "India",
    emoji: "🇮🇳",
    placeholder: "12ABCDE1234F1Z5",
  },
  {
    type: "is_vat",
    code: "IS VAT",
    name: "Iceland",
    emoji: "🇮🇸",
    placeholder: "123456-7890",
  },
  {
    type: "jp_cn",
    code: "JP CN",
    name: "Japan",
    emoji: "🇯🇵",
    placeholder: "123456789012",
  },
  {
    type: "jp_rn",
    code: "JP RN",
    name: "Japan",
    emoji: "🇯🇵",
    placeholder: "123456789012",
  },
  {
    type: "jp_trn",
    code: "JP TRN",
    name: "Japan",
    emoji: "🇯🇵",
    placeholder: "123456789012",
  },
  {
    type: "ke_pin",
    code: "KE PIN",
    name: "Kenya",
    emoji: "🇰🇪",
    placeholder: "12345678A",
  },
  {
    type: "kr_brn",
    code: "KR BRN",
    name: "South Korea",
    emoji: "🇰🇷",
    placeholder: "1234567890",
  },
  {
    type: "li_uid",
    code: "LI UID",
    name: "Liechtenstein",
    emoji: "🇱🇮",
    placeholder: "CHE-123.456.789",
  },
  {
    type: "mx_rfc",
    code: "MX RFC",
    name: "Mexico",
    emoji: "🇲🇽",
    placeholder: "XAXX010101000",
  },
  {
    type: "my_frp",
    code: "MY FRP",
    name: "Malaysia",
    emoji: "🇲🇾",
    placeholder: "123456789012",
  },
  {
    type: "my_itn",
    code: "MY ITN",
    name: "Malaysia",
    emoji: "🇲🇾",
    placeholder: "123456789012",
  },
  {
    type: "my_sst",
    code: "MY SST",
    name: "Malaysia",
    emoji: "🇲🇾",
    placeholder: "123456789012",
  },
  {
    type: "no_vat",
    code: "NO VAT",
    name: "Norway",
    emoji: "🇳🇴",
    placeholder: "123456789",
  },
  {
    type: "nz_gst",
    code: "NZ GST",
    name: "New Zealand",
    emoji: "🇳🇿",
    placeholder: "123456789",
  },
  {
    type: "ph_tin",
    code: "PH TIN",
    name: "Philippines",
    emoji: "🇵🇭",
    placeholder: "123-456-789-012",
  },
  {
    type: "ru_inn",
    code: "RU INN",
    name: "Russia",
    emoji: "🇷🇺",
    placeholder: "123456789012",
  },
  {
    type: "ru_kpp",
    code: "RU KPP",
    name: "Russia",
    emoji: "🇷🇺",
    placeholder: "123456789",
  },
  {
    type: "sa_vat",
    code: "SA VAT",
    name: "Saudi Arabia",
    emoji: "🇸🇦",
    placeholder: "123456789012",
  },
  {
    type: "sg_gst",
    code: "SG GST",
    name: "Singapore",
    emoji: "🇸🇬",
    placeholder: "123456789",
  },
  {
    type: "sg_uen",
    code: "SG UEN",
    name: "Singapore",
    emoji: "🇸🇬",
    placeholder: "123456789",
  },
  {
    type: "si_tin",
    code: "SI TIN",
    name: "Slovenia",
    emoji: "🇸🇮",
    placeholder: "12345678",
  },
  {
    type: "th_vat",
    code: "TH VAT",
    name: "Thailand",
    emoji: "🇹🇭",
    placeholder: "1234567890123",
  },
  {
    type: "tr_tin",
    code: "TR TIN",
    name: "Turkey",
    emoji: "🇹🇷",
    placeholder: "1234567890",
  },
  {
    type: "tw_vat",
    code: "TW VAT",
    name: "Taiwan",
    emoji: "🇹🇼",
    placeholder: "12345678",
  },
  {
    type: "ua_vat",
    code: "UA VAT",
    name: "Ukraine",
    emoji: "🇺🇦",
    placeholder: "12345678",
  },
  {
    type: "us_ein",
    code: "US EIN",
    name: "United States",
    emoji: "🇺🇸",
    placeholder: "12-3456789",
  },
  {
    type: "za_vat",
    code: "ZA VAT",
    name: "South Africa",
    emoji: "🇿🇦",
    placeholder: "1234567890",
  },
  {
    type: "ar_cuit",
    name: "Argentina",
    code: "AR CUIT",
    emoji: "🇦🇷",
    placeholder: "12-3456789-01",
  },
  {
    type: "co_nit",
    name: "Colombia",
    code: "CO NIT",
    emoji: "🇨🇴",
    placeholder: "123.456.789-0",
  },
  {
    type: "pe_ruc",
    name: "Peru",
    code: "PE RUC",
    emoji: "🇵🇪",
    placeholder: "12345678901",
  },
  {
    type: "vn_mst",
    name: "Vietnam",
    code: "VN MST",
    emoji: "🇻🇳",
    placeholder: "1234567890",
  },
  {
    type: "bd_bin",
    name: "Bangladesh",
    code: "BD BIN",
    emoji: "🇧🇩",
    placeholder: "123456789-0123",
  },
  {
    type: "cr_nite",
    name: "Costa Rica",
    code: "CR NITE",
    emoji: "🇨🇷",
    placeholder: "1-234-567890",
  },
] as const;
